const CATALOG_PRODUCTS = [
  {
    id: 1,
    title: "Canon Cmera EOS 2000, Black 10x zoom",
    price: 998.0,
    oldPrice: 1128.0,
    rating: 4.8,
    reviews: 32,
    orders: 154,
    sold: 154,
    image: "../../assets/Image/tech/image 23.png",
    alt: "Red smartphone",
    category: "Mobile accessory",
    type: "Smartphone",
    material: "Glass and aluminum",
    design: "Modern full-screen display",
    customization: "Logo and package options available",
    warranty: "2 years full warranty",
    supplier: "Guanjoi Trading LLC",
    description: "High-resolution mobile device with bright display, smooth touch response, and reliable battery life for daily use.",
    thumbnails: [
      "../../assets/Image/tech/image 23.png",
      "../../assets/Image/tech/image 32.png",
      "../../assets/Image/tech/6.png",
      "../../assets/Image/tech/image 85.png",
      "../../assets/Image/tech/image 86.png",
      "../../assets/Image/tech/image 34.png",
    ],
  },
  {
    id: 2,
    title: "GoPro HERO6 4K Action Camera - Black",
    price: 998.0,
    oldPrice: 1128.0,
    rating: 4.5,
    reviews: 28,
    orders: 154,
    sold: 154,
    image: "../../assets/Image/tech/image 32.png",
    alt: "Tablet computer",
    category: "Mobile accessory",
    type: "Tablet device",
    material: "Metallic body",
    design: "Slim portable design",
    customization: "Custom package available",
    warranty: "1 year seller warranty",
    supplier: "Best Factory LLC",
    description: "Compact tablet for browsing, media, and work with a clean display and portable body.",
    thumbnails: [
      "../../assets/Image/tech/image 32.png",
      "../../assets/Image/tech/image 23.png",
      "../../assets/Image/tech/6.png",
      "../../assets/Image/tech/image 29.png",
      "../../assets/Image/tech/image 34.png",
      "../../assets/Image/tech/8.png",
    ],
  },
  {
    id: 3,
    title: "Canon EOS Camera with premium zoom lens",
    price: 699.5,
    oldPrice: 899.0,
    rating: 4.7,
    reviews: 45,
    orders: 128,
    sold: 128,
    image: "../../assets/Image/tech/6.png",
    alt: "Canon camera",
    category: "Camera",
    type: "Digital camera",
    material: "Plastic and glass",
    design: "Classic camera body",
    customization: "Lens bundle options",
    warranty: "2 years full warranty",
    supplier: "Artel Market",
    description: "Digital camera with sharp lens, strong zoom range, and dependable controls for creators.",
    thumbnails: [
      "../../assets/Image/tech/6.png",
      "../../assets/Image/tech/image 23.png",
      "../../assets/Image/tech/image 34.png",
      "../../assets/Image/tech/image 29.png",
      "../../assets/Image/tech/image 86.png",
      "../../assets/Image/tech/image 85.png",
    ],
  },
  {
    id: 4,
    title: "Electric kettle for home and office kitchen",
    price: 79.5,
    oldPrice: 129.0,
    rating: 4.4,
    reviews: 18,
    orders: 96,
    sold: 96,
    image: "../../assets/Image/tech/image 85.png",
    alt: "Electric kettle",
    category: "Home appliance",
    type: "Kitchen appliance",
    material: "Stainless steel",
    design: "Minimal black finish",
    customization: "Custom package available",
    warranty: "1 year warranty",
    supplier: "Kitchen Pro LLC",
    description: "Compact electric kettle with simple controls and a clean matte finish for daily use.",
    thumbnails: [
      "../../assets/Image/tech/image 85.png",
      "../../assets/Image/interior/3.png",
      "../../assets/Image/interior/6.png",
      "../../assets/Image/interior/image 93.png",
      "../../assets/Image/interior/8.png",
      "../../assets/Image/interior/9.png",
    ],
  },
  {
    id: 5,
    title: "Gaming headset with microphone and blue trim",
    price: 129.5,
    oldPrice: 199.0,
    rating: 4.9,
    reviews: 62,
    orders: 210,
    sold: 210,
    image: "../../assets/Image/tech/image 29.png",
    alt: "Gaming headset",
    category: "Headphones",
    type: "Gaming accessory",
    material: "Plastic and soft foam",
    design: "Over-ear gaming design",
    customization: "Logo printing available",
    warranty: "2 years full warranty",
    supplier: "Audio Gear LLC",
    description: "Comfortable gaming headset with clear mic pickup, soft ear pads, and vivid blue trim.",
    thumbnails: [
      "../../assets/Image/tech/image 29.png",
      "../../assets/Image/tech/image 86.png",
      "../../assets/Image/tech/image 34.png",
      "../../assets/Image/tech/image 23.png",
      "../../assets/Image/tech/8.png",
      "../../assets/Image/tech/image 32.png",
    ],
  },
  {
    id: 6,
    title: "Wireless white headphones for music and calls",
    price: 89.5,
    oldPrice: 140.0,
    rating: 4.2,
    reviews: 21,
    orders: 81,
    sold: 81,
    image: "../../assets/Image/tech/image 86.png",
    alt: "White headphones",
    category: "Headphones",
    type: "Wireless audio",
    material: "Plastic and leather",
    design: "Lightweight over-ear",
    customization: "Color options available",
    warranty: "1 year warranty",
    supplier: "Audio Gear LLC",
    description: "Lightweight wireless headphones for travel, calls, and daily listening.",
    thumbnails: [
      "../../assets/Image/tech/image 86.png",
      "../../assets/Image/tech/image 29.png",
      "../../assets/Image/tech/image 23.png",
      "../../assets/Image/tech/image 32.png",
      "../../assets/Image/tech/8.png",
      "../../assets/Image/tech/image 34.png",
    ],
  },
  {
    id: 7,
    title: "Smart watch with silver strap and black display",
    price: 120.0,
    oldPrice: 180.0,
    rating: 4.8,
    reviews: 54,
    orders: 190,
    sold: 190,
    image: "../../assets/Image/tech/8.png",
    alt: "Smart watch",
    category: "Wearables",
    type: "Smart watch",
    material: "Metal strap",
    design: "Square digital display",
    customization: "Band color options",
    warranty: "2 years full warranty",
    supplier: "Wearable Market",
    description: "Smart watch with fitness tracking, notifications, and a polished silver strap.",
    thumbnails: [
      "../../assets/Image/tech/8.png",
      "../../assets/Image/tech/image 86.png",
      "../../assets/Image/tech/image 23.png",
      "../../assets/Image/tech/image 32.png",
      "../../assets/Image/tech/image 85.png",
      "../../assets/Image/tech/image 29.png",
    ],
  },
  {
    id: 8,
    title: "Laptop Pro with retina screen and fast storage",
    price: 870.0,
    oldPrice: 1099.0,
    rating: 4.6,
    reviews: 37,
    orders: 112,
    sold: 112,
    image: "../../assets/Image/tech/image 34.png",
    alt: "Laptop",
    category: "Computers",
    type: "Laptop",
    material: "Aluminum",
    design: "Thin laptop body",
    customization: "Memory and storage options",
    warranty: "2 years full warranty",
    supplier: "Computer Hub LLC",
    description: "Portable laptop with sharp display, fast storage, and dependable daily performance.",
    thumbnails: [
      "../../assets/Image/tech/image 34.png",
      "../../assets/Image/tech/image 32.png",
      "../../assets/Image/tech/6.png",
      "../../assets/Image/tech/image 23.png",
      "../../assets/Image/tech/image 29.png",
      "../../assets/Image/tech/image 86.png",
    ],
  },
  {
    id: 9,
    title: "Mens Long Sleeve T-shirt Cotton Base Layer Slim Muscle",
    price: 98.0,
    oldPrice: 140.0,
    rating: 4.7,
    reviews: 32,
    orders: 154,
    sold: 154,
    image: "../../assets/Layout/alibaba/Image/cloth/Bitmap.png",
    alt: "Blue shirt",
    category: "Clothing",
    type: "Classic shirt",
    material: "Cotton blend",
    design: "Modern slim fit",
    customization: "Customized logo and design custom packages",
    warranty: "2 years full warranty",
    supplier: "Guanjoi Trading LLC",
    description: "Soft cotton base layer shirt with slim fit styling for men and daily casual wear.",
    thumbnails: [
      "../../assets/Layout/alibaba/Image/cloth/Bitmap.png",
      "../../assets/Layout/alibaba/Image/cloth/2 1.png",
      "../../assets/Layout/alibaba/Image/cloth/image 30.png",
      "../../assets/Layout/alibaba/Image/cloth/Bitmap (2).png",
      "../../assets/Layout/alibaba/Image/cloth/image 26.png",
      "../../assets/Layout/alibaba/Image/cloth/image 24.png",
    ],
  },
];

function findCatalogProduct(id) {
  return CATALOG_PRODUCTS.find((product) => product.id === Number(id)) || CATALOG_PRODUCTS[0];
}
